Setup docker container for the application
bartius-nigel/weather-comparitor pull request #58
Opened 2020-10-01 20:45 UTC by elaynelemos

Closes #43 

Hey! This is my contribution as I told at the [issue](https://github.com/bartius-nigel/weather-comparitor/issues/43#issuecomment-699699349).

#### How to analyse this PR
- Build the container with
```bash
docker-compose up -d weather-app
```
- Build and run the application with
```
./run.sh npm install
# served at http://localhost:5000
./run.sh npm run dev
```
- Try some commands with
```
./run.sh [COMMAND]
```

The base container chosen was [node](https://hub.docker.com/_/node):12-buster-slim. You can find instructions also at the README.md file.

2020-10-02 00:31 UTC, bartius-nigel requested changes
just one minor comment regarding some spelling, but looks good to me. Thanks for the contribution!!

2020-10-02 00:31 UTC, bartius-nigel commented on docker-compose.yml
> +    container_name: wheater_comparitor_app
```suggestion
    container_name: weather_comparitor_app
```

2020-10-02 10:52 UTC, elaynelemos commented on docker-compose.yml
> +    container_name: wheater_comparitor_app
Woow, thank you! I just fixed it. :smile_cat:

2020-10-03 15:47 UTC, bartius-nigel approved these changes

2020-10-03 15:49 UTC, merged

2020-10-03 16:04 UTC, bartius-nigel commented
Thank you so much @elaynelemos !!

2020-10-03 16:44 UTC, elaynelemos commented
> Thank you so much @elaynelemos !!

My pleasure! :smile_cat: