[Tests-Only]Added a sample e2e test along with setup for cypress
bartius-nigel/weather-comparitor pull request #61
Opened 2020-10-04 10:51 UTC by Talank

### Description
I did the set up of `cypress` in this project and wrote a very basic UI test as a proof of concept. According to the readme file, in order to run the project locally, after installing the project (with `./run.sh npm install`)we have to run the following commands consecutively
1) run the docker app `docker-compose up -d weather-app`
2) `./run.sh npm run dev`

Now test can be run with an additional script `npm run test-e2e`. 

### Related Issues
- part of https://github.com/bartius-nigel/weather-comparitor/issues/13

### How this has been tested?
- By running the tests locally

2020-10-04 19:17 UTC, bartius-nigel requested changes
looks pretty sweet dude! thanks for putting that together. Just one minor comment and i'll approve

2020-10-04 19:17 UTC, bartius-nigel commented on cypress/integration/examples/searchCity.spec.js
> +            cy.get('button.svelte-mhoz42').click()
i think this css class might be auto generated each time the app is run. Possibly not but it would be better if a different path was used. Would you mind updating that?

2020-10-05 05:35 UTC, Talank commented
Sure, I have changed the selector for the finding that `Enter` button.

2020-10-07 03:48 UTC, Talank commented
@bartius-nigel do I need to make any other changes? Please review again

2020-10-07 04:17 UTC, bartius-nigel approved these changes
looks good man! thanks for the contribution. I just had a couple busy days at work so i was delayed on this.

2020-10-07 04:17 UTC, merged