[UI] fix the colors and difference in weather table
bartius-nigel/weather-comparitor pull request #65
Opened 2020-12-03 06:39 UTC by dpakach

Fix the weather table to show the difference properly.

Hello @bartius-nigel, I just changed few UI elements to make the table look better. Please have a look and merge if you like. :+1: 

Before the changes:
![Screenshot from 2020-12-03 12-21-37](https://user-images.githubusercontent.com/19869344/100973235-496ed700-3562-11eb-8e2d-7c1801583c6c.png)

After the changes:
![Screenshot from 2020-12-03 12-21-11](https://user-images.githubusercontent.com/19869344/100973249-51c71200-3562-11eb-92cf-540c27ad8cda.png)

2020-12-03 17:22 UTC, bartius-nigel commented
I quite like that. Ill take a look at it later today (at work now)

2020-12-04 05:28 UTC, bartius-nigel requested changes
This all looks really awesome. Thank you, just need some minor tweaks. Also, could you update the tests so that they pass? the CI wont let me merge this until that happens

2020-12-04 05:28 UTC, bartius-nigel commented on src/components/Difference.svelte
> -    font-size: 0.0000001em;
Can you change this to a different unit than em, i think the different browsers interpret this differently.

2020-12-04 05:28 UTC, bartius-nigel commented on src/components/WeatherTable.svelte
> +  tr {
I like this, but could we change the background color to the white?

2020-12-04 05:28 UTC, bartius-nigel commented on src/components/Difference.svelte
> +  <div>
is it possible to just delete the div?

2020-12-07 12:31 UTC, dpakach commented on src/components/Difference.svelte
> -    font-size: 0.0000001em;
I believe `em` and `rem` are based on the font size of the parent elements, so this shouldn't bring any inconsistency between browsers. I checked on firefox and chrome both looks ok

2020-12-08 02:47 UTC, merged